<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Top Pack</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

        <link href='./css/search.css' rel='stylesheet' type='text/css'>
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.7/angular.js"></script>
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.7/angular-route.js"></script>
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.7/angular-resource.js"></script>
        <script type="text/javascript" src="./config.js"></script>
        <script type="text/javascript" src="./route.js"></script>
        <script type="text/javascript" src="./services/toppack-service.js"></script>
        <script type="text/javascript" src="./controllers/toppack-controller.js"></script>
    </head>
    <body>
       <div ng-app="toppack">
           <ng-view></ng-view>
       </div>
    </body>
</html>
